In [2]:
import torch

batch_size = 3
seq_len = 5

padding_mask = torch.zeros(batch_size, seq_len, dtype=torch.bool)

In [4]:
print(padding_mask)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [5]:
lengths = [3, 5, 2]

for i, l in enumerate(lengths):
    print(i, l)

0 3
1 5
2 2


In [6]:
for i, l in enumerate(lengths):
    padding_mask[i, l:] = True

padding_mask

tensor([[False, False, False,  True,  True],
        [False, False, False, False, False],
        [False, False,  True,  True,  True]])

In [7]:
print(padding_mask)

tensor([[False, False, False,  True,  True],
        [False, False, False, False, False],
        [False, False,  True,  True,  True]])
