In [2]:
import torch

batch_size = 3
seq_len = 5

padding_mask = torch.zeros(batch_size, seq_len, dtype=torch.bool)

In [4]:
print(padding_mask)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [5]:
lengths = [3, 5, 2]

for i, l in enumerate(lengths):
    print(i, l)

0 3
1 5
2 2


In [6]:
for i, l in enumerate(lengths):
    padding_mask[i, l:] = True

padding_mask

tensor([[False, False, False,  True,  True],
        [False, False, False, False, False],
        [False, False,  True,  True,  True]])

In [7]:
print(padding_mask)

tensor([[False, False, False,  True,  True],
        [False, False, False, False, False],
        [False, False,  True,  True,  True]])


In [20]:
x = torch.randn(2, 3, 224, 224)
x.shape

torch.Size([2, 3, 224, 224])

In [12]:
x.unfold(2, 16, 16).shape

torch.Size([2, 3, 14, 224, 16])

In [21]:
x = x.unfold(2, 16, 16).unfold(3, 16, 16)

In [23]:
x = x.permute(0, 2, 3, 1, 4, 5).contiguous()
x.shape

torch.Size([2, 14, 14, 3, 16, 16])

In [24]:
x = x.view(2, -1, 3 * 16 * 16)

In [25]:
x.shape

torch.Size([2, 196, 768])

In [27]:
y = torch.randn(2, 3, 2)
y

tensor([[[-1.0377,  0.8205],
         [ 1.2192, -1.0159],
         [-0.5402, -0.9473]],

        [[ 0.7992, -0.9455],
         [-1.0389,  1.0906],
         [-0.3926, -0.2801]]])

In [33]:
z = y.unfold(0, 1, 1)
z.shape , z

(torch.Size([2, 3, 2, 1]),
 tensor([[[[-1.0377],
           [ 0.8205]],
 
          [[ 1.2192],
           [-1.0159]],
 
          [[-0.5402],
           [-0.9473]]],
 
 
         [[[ 0.7992],
           [-0.9455]],
 
          [[-1.0389],
           [ 1.0906]],
 
          [[-0.3926],
           [-0.2801]]]]))