In [1]:
import torch

In [2]:
x = torch.rand((2,3))

In [3]:
x

tensor([[0.3109, 0.4111, 0.5022],
        [0.0474, 0.1615, 0.8611]])

In [7]:
# Permutation
a = torch.einsum("ij->ji", x)

In [ ]:
a

In [9]:
# Summation
s = torch.einsum("ij->", x)

In [10]:
s

tensor(2.2943)

In [11]:
# Column sum
c = torch.einsum("ij->j", x)
c

tensor([0.3584, 0.5726, 1.3633])

In [12]:
# Column sum
r = torch.einsum("ij->i", x)
r

tensor([1.2242, 1.0701])

In [15]:
# Matrix Vector multiplication
v = torch.rand((3,1))
mv = torch.einsum("ij,kj->ik", x, v)
mv

tensor([[0.1391, 0.7183, 0.5093],
        [0.1216, 0.6278, 0.4452]])

In [16]:
# Matrix matrix multiplication
m1 = torch.rand((3,2))
mm = torch.einsum("ij,jk->ik", x, m1)
mm

tensor([[0.1092, 0.6791],
        [0.0908, 0.7158]])

In [18]:
d = torch.rand((3,3))
print(d)
dd = torch.einsum("ii->i", d)
dd

tensor([[0.2535, 0.9362, 0.9477],
        [0.6600, 0.0471, 0.7584],
        [0.4145, 0.1339, 0.5169]])


tensor([0.2535, 0.0471, 0.5169])